name: Publish PowerShell Module

on: push

jobs:
  pester-test:
    name: Pester test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Perform a Pester test from the Tests.ps1 file
        shell: pwsh
        run: |
          $pesterContainer = New-PesterContainer -Path ".\tests\PowerShell.Wiz.Utility.Tests.ps1" -Data @{ param = 1 }
          Invoke-Pester .\tests\ 

  # publish-to-gallery:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Publish
  #       env:
  #         NUGET_KEY: $PS_GALLERY_KEY
  #       shell: pwsh
  #       run: |
  #         Publish-Module -Path . -NuGetApiKey ${{secrets.PS_GALLERY_KEY}} -Verbose
